docs/index.md
docs/tools.md

Small tweaks and content

---

docs/index.md

Just a few minor suggestions and typos for the top index page.

some small changes to docs

---

docs/index.md

Amazing work on this!
I just referenced this to my brother @anderssundell who is building https://www.stathelp.se/ for his students at Gothenburg University in Sweden.

Fix of broken link to github org

---

.readthedocs.yml
dev-conventions.md
docs/dev-conventions.md
docs/index.md
docs/team_panels_code.txt

As discussed in #74 
This page should also be linked to in the EBP repositories

Add development conventions

---

docs/feature-vote.md

Makes the feature voting window full-width

👌 IMPROVE: feature vote full width

---

docs/developer.md
docs/index.md

This PR adds a small section with some helpful tips for getting access to a documents xml structure to visualise the sphinx.AST

📚 DOCS: Add developer tips and tricks section

---

docs/_templates/layout.html

🐛 BUG: Sorting upvotes by numbers not strings

---

docs/gallery.yml

Adding the [neural process family book](https://yanndubs.github.io/Neural-Process-Family/) to the gallery.

📚 DOCS: [Gallery] adding neural process family.

---

docs/gallery.yml

Added two additional Jupyter books focused on neuroimaging data analysis. One is still using old version of jupyterbook. Will upgrade that one in the next couple of weeks.

📚 DOCS: Update gallery.yml

---

docs/gallery.yml

I'm sorry @jmason86 and I didn't get to this before PR #181 was merged.

📚 DOCS: Added the Jupyter Book HelioML

---

docs/conf.py
docs/gallery.yml

📚 DOCS: Updated broken path to HelioML logo

---

docs/gallery.yml

Hi all 👋 Just adding The Turing Way to your gallery of Jupyter Books. We love this project so much, thanks for all the hard work!

📚 DOCS: Add The Turing Way to JupyterBook Gallery

---

docs/gallery.yml

Added deep learning for molecules and materials by Andrew White. Thanks!

📚 DOCS: Added new gallery content

---

docs/gallery.yml

Adding the arts engagement project to the gallery of examples. Thanks for all the hard work!

📚 DOCS: Added artsengagement project to gallery.yml

---

docs/gallery.yml

Adding my "Python for Data Science" Jupyter Book to the ever-expanding gallery of examples! Thanks for the ongoing hard work!

📚 DOCS: Added python for data science jupyter book to gallery.yml

---

docs/gallery.yml

Add "PyTorch를 활용한 딥러닝 튜토리얼 (Deep Learning Tutorials with PyTorch)"

DOC: Add one to gallery.yml

---

docs/gallery.yml

This has the correct title (with quotes) and image path!

📚 DOCS: Add intropy book to gallery

---

docs/Makefile
docs/index.md

closes https://github.com/executablebooks/meta/issues/227

📚 DOCS: fixing blog link

---

docs/gallery.yml

This is an example of Jupyter Book written in french. There is no code inside but perhaps my config and some customisation I made could help.
- Insert a latex file between title page and table of contents
- Change style of admonition class with custom.css
- Set a specific numbering
I comment some issues and you always answer kindly and very quickly. Thanks again.
PS: There still this non-translated preposition "by" in the footer but it is already fixed for the next release.

📚 DOCS: adding entry to gallery

---

docs/gallery.yml

📚 DOCS: Add Learn Python Programming book to gallery

---

docs/gallery.yml

Callysto (https://www.callysto.ca/ ) is a Canadian non-profit whose mission is "to help students and teachers grow and develop data literacy skills". One of the ways we do that is by developing curriculum modules in Jupyter notebooks and offer a service that runs those notebooks (hub.callysto.ca). This Jupyter book submission is a compilation of all our individual learning modules organized by subject.

📚 DOCS: Callysto Curriculum in gallery

---

docs/gallery.yml

I put the sources on GitHub which is more convenient. Sorry for the extra work.

📚 DOCS: Change an url in gallery

---

docs/gallery.yml

Adding the [Development Data Partnership](https://docs.datapartnership.org/) to the gallery :tada:.

📚 DOCS: Add Development Data Partnership to gallery

---

docs/gallery.yml

Adding TensorDiffEq documentation to project zoo

📚 DOCS: Add TensorDiffEq Docs to project list

---

docs/gallery.yml

… python ISA-API
Documentation for the Investigation Study Assay (ISA) python API

📚 DOCS: Add python ISA-API to gallery

---

docs/gallery.yml

Thanks for the amazing executable books project!

📚 DOC: Add MalariaGEN Vector Data User Guide to gallery

---

docs/gallery.yml

add scikit-learn course by [INRIA](https://github.com/INRIA)

📚 DOCS: Added Scikit-learn course to gallery.yml 

---

docs/gallery.yml

Added the right image URL this time :-)

Update to epidemic modelling book

---

docs/gallery.yml

Added the Argo Online School - The Argo Online school is a set jupyter notebooks to describe the minimum requirements to use, and understand, the Argo data.

Update gallery.yml - added the Argo Online School

---

docs/gallery.yml

update gallery with "Programming Differential Privacy" book listing

update gallery with new book

---

docs/conf.py

closes https://github.com/executablebooks/meta/issues/395

📚 DOCS: Updating logo for books with missing image

---

docs/gallery.yml

FYI: @kanderso-nrel , @shirubana , @wholmgren , @cwhanse

📚DOCS: Add pvlib python PVSC tutorial to gallery

---

docs/index.md
docs/meetings/2021.md
docs/meetings/index.md

Add notes from our last meeting, also adds a short paragraph about the Sloan foundation
closes #397

📚 DOCS: Add meeting notes

---

README.md
docs/conf.py
docs/meetings/index.md
docs/team_panels_code.txt
tox.ini

- Fixes our calendar so it is public
- Updates the `ghapi` code so that it properly uses an access token if one exists

Fix calendar and other minor fixes

---

docs/gallery.yml

The first complete version of the text as a JupyterBook is now live! 🎉

📚 DOCS: add An Introduction to Applied Bioinformatics

---

docs/gallery.yml

updating gallery.yml with Ryan C. Cooper - Computational Mechanics course website.

updating gallery.yml with Computational Mechanics

---

docs/gallery.yml

Finally got around to convert one of my courses. Thanks a lot for setting up the project!

📚 DOCS: Add topology course to the gallery

---

docs/meetings/2021.md
docs/updates/2021-06-18-update-toc.md

This PR adds minutes from today's monthly team meeting

📚 DOCS: add meeting minutes from 5th August Team Meeting

---

docs/gallery.yml

Adds new project to Jupyter Books gallery.

Add VisDepot project to gallery

---

docs/gallery.yml

Add jupyter-book **Data Science Process using CRISP-DM** to the gallery.

docs: add data science process using crisp-dm book

---

docs/meetings/2021.md

These are the meeting notes from last October's meeting.
closes #507

Add october meeting notes

---

docs/gallery.yml

Now with the title in quotes so RTD doesn't crash!

Update gallery.yml with NI-edu book

---

docs/gallery.yml

Add Intro to Data Science For Engineers book

---

docs/meetings/2021.md

Notes from the Dec 2021 meeting
closes https://github.com/executablebooks/meta/issues/560

Add notes from december meeting

---

docs/updates/2021-12-18-agu-2021.md

This is a short blog post that shares some links to videos + slides for a few talks I gave at AGU 2021 this year.

BLOG: Jupyter book at AGU 2021

---

docs/gallery.yml

Hello all, 
Thanks for the jupyter-book, it has become my one of the favorite packages.
I am working on a creative way of creating Python courses.
**Idea of Prodigious Python is to be different from the traditional books.**
We wanted Prodigious Python to be:
Fun 🎉
Executable 🤖
Publishable via static web pages and PDF ⚙️

ENH: Add to gallery

---

docs/gallery.yml

Book available [here](https://aeturrell.github.io/coding-for-economists). Thanks for the amazing package!

Include 'coding for economists'

---

docs/gallery.yml

Hi, thank you for this wonderful tool! My jupyter book is for a genomic analysis package. Hope it's suitable to add in here.
Best Regards
Hanqing

DOCS: Add website to gallery

---

docs/gallery.yml

Adds a short course on network data science to the gallery

NEW: Add network data science course

---

docs/gallery.yml

Proposed addition to gallery: my lectures notes for a course on Inverse Problems in Imaging.

DOCS: Add to `gallery.yml`

---

docs/gallery.yml

This doesn't seem to exist anymore

Remove the ISA cookbook

---

docs/gallery.yml

Added my Scientific Computing for Chemists JupyterBook to the gallery.yml file to be included in the Gallery of Jupyter Books.

Added SciCompChem book to gallery.yml file

---

docs/meetings/2022.md

Adds our meeting notes from the last meeting.
closes https://github.com/executablebooks/meta/issues/679

MEETING: March 2022

---

docs/conf.py

closes https://github.com/executablebooks/meta/issues/695

Add repository links

---

docs/gallery.yml

We would like to add our ongoing project containing tutorials and educational materials on computational chemistry to your gallery

Add eChem to gallery

---

docs/gallery.yml

Adds https://living-with-machines.github.io/genre-classification/intro.html to the gallery of Jupyter Books

add genre classification book to gallery

---

docs/gallery.yml

"Introduction à la PROgrammation Scientifique" is a collection of  IPython educational notebooks in French for undergraduate students, to learn the basics of scientific programming using Python. Short videos are included in the notebooks as well as many application examples, particularly in the field of mechanics.

Add gallery entry

---

docs/gallery.yml

This PR adds a graduate course I developed using the wonderful `jupyter-book` project - thank you for creating this tool!

Add physics course to gallery

---

docs/gallery.yml

A new Jupyter notebook to add to the gallery.
https://applying-maths-book.com/

Add Applying Maths in the Chemical and Biomolecular Sciences book

---

docs/gallery.yml

This adds another example to the Jupyter Book Gallery

Add CCD reduction guide

---

docs/gallery.yml

Add [Simply Logical](https://book.simply-logical.space/) to the [Jupyter Book gallery](https://executablebooks.org/en/latest/gallery.html).

Add "Simply Logical" to the gallery

---

docs/gallery.yml

There's an overview of what it's about at https://twitter.com/petebankhead/status/1516729400137551878?s=20&t=z_79jChbpBQTZav00C9eCg
(Thanks for all the Jupyter Book work that made it possible!)

DOCS: Add Introduction to Bioimage Analysis to gallery

---

docs/gallery.yml

DOC: Add book to gallery

---

docs/meetings/2022.md
docs/team_panels_code.txt

DOCS: Add meeting minutes for April

---

docs/gallery.yml

This PR adds a the Environmental Data Science Book, a community-driven and open-source resource powered by the wonderful `jupyter-book` project - Thank you

Add EDS book to gallery.yml

---

docs/gallery.yml

Added the open Security Reference Architecture book as example, created with JupyterBook tool chain.

Add book to gallery.yml

---

docs/gallery.yml

We wrote a book on network machine learning with jupyter book.
Currently accepted by both Springer and Cambridge, with free online versions allowed. Adding it to this repo.

Add hands-on network machine learning book

---

docs/gallery.yml

Here is our newly minted Jupyter book for the gallery list. I am loving using the Jupyter Book tools thus far. Thanks for your work and the excellent documentation.

add PmagPy book to book gallery.yml

---

docs/gallery.yml

It would be a pleasure to include our project to your list of books.
`HPX` is a C++ Standard Library for Concurrency and Parallelism. It implements all of the corresponding facilities as defined by the C++ Standard. Additionally, in HPX we implement functionalities proposed as part of the ongoing C++ standardization process and we also extend the C++ Standard APIs to the distributed case.
@hkaiser

Update gallery of books to include `HPX`

---

docs/conf.py
requirements.txt

Adds a redirection for our old blog post title. I'm gonna try the old post link in the docs preview and if it works, I'll merge so that we un-break the old links.

MNT: Add sphinxext rediraffe redirections

---

docs/gallery.yml

This PR adds the geemap book - https://book.geemap.org/

Add geemap book

---

docs/gallery.yml

Very proud user. Jupyter-book rocks!

Added Kinetics Toolkit to gallery

---

docs/blog/2023-03-07-call-for-myst-templates.md

Thank you @riziles for catching this!

📆 Update year in blog post

---

docs/gallery.yml

cc @rossbar
We may need to tweak which logo to use, I'll wait for the CI rendering to check on it.

Adding the numpy tutorials

---

docs/gallery.yml

I don't yet have a logo for this, but will add one later when/if it becomes available.

Adding the NASA NAVO workshop notebooks

---

docs/gallery.yml

Logo may need adjustments, waiting for CI rendering

Adding the astroML interactive book

---

docs/conf.py

See https://github.com/orgs/executablebooks/discussions/999

🐛 Update the footer year

---

docs/gallery.yml

cc @rossbar
again, logo may need adjustments

Adding the networkx guides

---

docs/gallery.yml

This is a book containing step by step instructions to train deep learning models for a variety of tasks - https://bipinkrishnan.github.io/ml-recipe-book

Add machine learning recipe book

---

docs/blog/2023-06-27-jupyterlab-myst.md

Both work, but second one trims out a bit of the start!

📺 Update video link to webinar

---

docs/gallery.yml

update outdated link for The data science interview book

[FIX] Update gallery.yml - The data science interview book

---

requirements.txt

This ensures social cards are built

Adding matplotlib

---

.readthedocs.yml
docs/gallery.yml

This should fix the RTD build failure we see

CI: adding explicit sphinx config into RTD config

---

docs/blog/2020-08-07-announce-book.md
docs/gallery.yml

@vandesai1 - I'm adding the IRSA tutorials to the big notebook collection gallery (https://executablebooks.org/en/latest/gallery/) . Happy to add the fornax repo, too if you think it's ready for people to look at (though they are already looking based on the stars)

Adding Caltech/IPAC-IRSA tutorials

---

docs/feature-vote.md

While looking at the the feature board I noticed that there are no more "+" around, so better remove the sentence from the docs.

DOC: there is no "+" any more.

---

docs/gallery.yml

Add MUDE Book to Gallery
