executablebooks/meta

.gitignore
docs/conf.py
docs/index.md
docs/team.md
docs/team_panels_code.txt
docs/update_team.py

This adds a team page to our documentation by pulling the latest information from https://github.com/orgs/executablebooks/people . It uses @chrisjsewell 's sphinx-panels to do the rendering, which is awesomely easy

adding team page

---

docs/tools.md

The square bracket meant the link wasn´t rendered correctly in the final page:

Corrected link syntax in Tools > MyST section.

---

.gitignore
docs/conf.py
docs/examples.md
docs/index.md

This adds a little `requests` grab so we can use the latest `contributing.md` in our Sphinx documentation in meta. Also fixes a syntax bug in our examples page.

📚 DOCS: adding contributing guidelines from source

---

docs/gallery.yml

I've added an entry for my book, "Jupyter Guide to Linear Algebra".  I'm still working on minor additions and editing, but the book is useful in its current form and is approaching completion.  Thank you for your work on the tools to make this possible.  Jupyter book has provided a great authoring experience for the subject.

📚 DOCS: Update gallery.yml

---

docs/conf.py
docs/updates/2021-06-18-update-toc.md
docs/updates/2021-06-5-release-jb-v0.11.1.md

This is a short blog post to show how to migrate from the old TOC structure, which can refer to from the JB docs without going into too much detail there and cluttering up the docs.

📚 DOCS: blog post about new toc

---

.github/ISSUE_TEMPLATES/team-meeting.md
docs/index.md
docs/meetings.md
docs/updates/2021-06-18-update-toc.md

This adds some information about EBP team meetings, and adds links to a calendar with team meeting dates, as well as a HackMD with an agenda template.
It also proposes that we have **our first team meeting on Thursday, July 1st at 7am Sydney time**.
cc @executablebooks/ebpteam to see if this works for folks!
related to https://github.com/executablebooks/meta/issues/379

📚 DOCS: Add calendar

---

docs/gallery.yml

This adds the `jupyter-book` projects from `quantecon`

[GALLERY] add quantecon projects that have been migrated to jupyter-book

---

requirements.txt

Without this, sphinx v2 was being installed

🔧 MAINTAIN: Pin sphinx requirement to v3

---

.github/ISSUE_TEMPLATE/team-meeting.md
.github/workflows/create-meeting-issue.yml

This adds an action that will update a team meeting issue, so that we don't have to do it manually.
Since this is a minor change I'll plan to merge in a few days unless there are objections.

Automate team meeting issue update

---

.github/workflows/linkcheck.yml
docs/gallery.yml
docs/tools.md
docs/updates/2020-08-07-announce-book.md

This builds the documentation and runs a quick link check in an action on every push/pr. It uses the [lychee action](https://github.com/lycheeverse/lychee-action) and will fail tests if there's a broken link + print a text readout of the links that are not breaking that we can inspect to fix.
This will be particularly helpful for the gallery, to catch additions that break links, or links that have become outdated.

MAINT: Add a linkcheck action

---

.github/ISSUE_TEMPLATE/team-meeting.md
docs/meetings/2022.md
docs/meetings/index.md

Updates our meeting template a bit, so the information is more consistent and there's just a single source of truth for meeting time / calendar link. Also adds meeting notes from last meeting.
Assuming that tests are happy, I'll merge so that I can create a new issue template.

Add meeting notes and update template

---

docs/developer.md

Spelling error: "Developement" should be "Development." I assume that fixing this in the heading will cascade through naturally to the table of contents in the navigation sidebar.

STY, DOC: Fix spelling error in "developement"

---

.github/workflows/linkcheck.yml
requirements.txt

This unpins the sphinx version in these docs. I'm not sure why it was pinned so let's see if this breaks anything. If nothing breaks, then this closes #720

Unpin sphinx

---

docs/communication.md

Resolves #717 
`https://discuss.executablebooks.org/` currently does not properly resolve to the [executablebooks/meta](https://github.com/executablebooks/meta) [GitHub Discussions page](https://github.com/executablebooks/meta/discussions), so replace it directly with the URL to the GitHub Discussions.

FIX: Update GitHub Discussions Forum URL

---

docs/gallery.yml

Add the [pyhf](https://github.com/scikit-hep/pyhf) [user guide and tutorial](https://pyhf.github.io/pyhf-tutorial/) to the Gallery of Jupyter Books.
c.f. https://github.com/scikit-hep/pyhf
(cc @lukasheinrich @kratsg)

DOC: Add pyhf user guide and tutorial to gallery

---

docs/gallery.yml

Updated location of Scientific Computing for Chemists book due to merging book with another project.

Fix gallery link

---

docs/gallery.yml

Many images in the gallery are broken as they pull from github.com instead of githubusercontent.com. Fix this.

Fix: Use githubusercontent for images in gallery

---

.github/workflows/linkcheck.yml
docs/conf.py
docs/gallery.yml
docs/tools.md

Fixes our readthedocs builds, which I think have been broken once the MyST parser released a new version that changed the behavior on anchor links.
Also improves our link checker so that it adds a GitHub Actions summary in markdown when it fails.
Fixes a few links, but there are likely still some broken ones, will merge this one anyway so we un-break the docs.
closes https://github.com/executablebooks/meta/issues/765

Fix documentation build

---

docs/gallery.yml

[Neuolibre](https://neurolibre.org) is approaching its beta release to publish jupyter books as reproducible neuroscience preprints! This pull request adds first two jupyter books published on NeuroLibre. 
As website, I provided DOI links that resolve into the respective publication pages.  `Reproducible preprint` button takes the reader to the Jupyter Book page. HTML and binderhub are served from our production servers.  
Alternatively, archived books can be downloaded by clicking the `JupyterBook archive` button. 
If this convention will be followed for the foreseeable future, I can have our editorial bot [roboneuro](https://roboneuro.herokuapp.com/) to send automated PRs each time a JupyterBook is published.
Thank you for maintaining this amazing project!

Jupyter Books published by neurolibre.org

---

docs/gallery.yml

[CVE.icu](https://cve.icu) is a jupyterbook project I run to display CVE data from NVD and MITRE that is updated daily using github actions.   It would be amazing if it can be added to the gallery as an example.

Add CVE.icu to gallery of books

---

docs/index.md

Updates a myst.tools link to avoid redirects for folks who may not be able to access the myst.tools domain.

Update myst-tools link

---

docs/conf.py

I have not tested locally, but this seems to maybe be required? The current link from the website doesn't work!
Described in the docs here:
https://sphinx-book-theme.readthedocs.io/en/stable/customize/index.html?highlight=html_theme_options#theme-options

Update branch to main in "edit on github" button

---

docs/blog/2023-02-09-announce-mystjs.md

This PR removes `2023/` and replaces with the dated document structure

MAINT: remove 2023 folder in favour of dated docs

---

docs/conf.py

GhApi's `per_page` [is limited to 100](https://ghapi.fast.ai/page.html#paged-operations), so we must use pagination to read more than 100 entries. This is currently manifesting as missing entries in [the feature-voting table](https://executablebooks.org/en/latest/feature-vote/).

docs: use pagination for GhApi

---

docs/blog/2023-06-27-jupyterlab-myst.md

The commit that the links previously referenced doesn't exist anymore. This updates the raw GitHub CDN to main.

📺 Fix video links to main

---

docs/conf.py

This should fix our broken social previews :crossed_fingers:

Use trailing slash in URL for social cards

---

docs/gallery.yml

shortening the link fixes the problem where the number of GitHub stars is not displayed.

use a shorter version of repository link

---

.github/dependabot.yml

This should have been done in #1219

MAINT: grouping dependabot version bumps

---

docs/gallery.yml

https://whitead.github.io/dmol-book/ -> https://dmol.pub

fix URL redirect

---

.github/workflows/linkcheck.yml
docs/gallery.yml

So the broken links won't pop-up in PRs but separately in CI.

CI: Adding link check cronjob
